talkingPotato1906/developerWeek

- dv/lib/color_palette.dart
- dv/lib/main.dart
- dv/lib/menu/menu.dart
- dv/lib/settings/setting_screen.dart
- dv/lib/settings/theme/theme_provider.dart
- dv/pubspec.lock
- dv/pubspec.yaml
설정에서 테마 변경 기능 구현
드롭다운 박스에서 테마 선택. 테마 선택한 결과가 인덱스로 반환.
드롭다운 박스에서도 선택한 테마 볼 수 있도록 변경
https://github.com/user-attachments/assets/3628adf2-a4ca-4d68-af80-85689c5aec99
> Theme change

- dv/lib/main.dart
- dv/lib/menu/menu.dart
- dv/lib/settings/setting_screen.dart
- dv/lib/settings/theme/theme_provider.dart
- dv/lib/title/title_screen.dart
- dv/macos/Flutter/GeneratedPluginRegistrant.swift
- dv/pubspec.lock
- dv/pubspec.yaml
> 🎨 배경색 테마 적용 방식 변경

- dv/lib/color_palette.dart
- dv/lib/menu/menu.dart
- dv/lib/settings/setting_screen.dart
- dv/lib/settings/theme/theme_provider.dart
테마 전환 성공. 이후 테마 별 폰트 색 등 조정 추가
https://github.com/user-attachments/assets/8035cf23-728c-4023-b279-b9020b98e0dc
> 🎨 테마 전환 방법 수정3

- dv/lib/gallery/showroom.dart
- dv/lib/gallery/swipe_page_view.dart
- dv/lib/main.dart
> 🔥 필요없는 코드 삭제, main 파일의 내용 이동

- dv/lib/gallery/image_provider.dart
- dv/lib/gallery/photo.dart
- dv/lib/gallery/showroom.dart
1. 보관함에서 갤러리 추가 기능
2. 이미지 삭제/수정 기능
3. 갤러리 추가 시 9개 제한 기능 
4. 이미지 업로드 버튼을 하단으로 변경
> ✨ 보관함/갤러리 기능 추가 및 수정

- dv/lib/gallery/photo.dart
- dv/lib/gallery/showroom.dart
- dv/lib/settings/theme/color_palette.dart
- dv/lib/settings/theme/theme_changer.dart
- dv/lib/settings/theme/theme_provider.dart
> 🎨 Photo.dart, showroom.dart에 색상 추가

- dv/lib/menu/menu.dart
메뉴에서 로그인 상태일 때는 로그아웃 아이콘, 로그아웃 상태일 때는 로그인 아이콘이 뜨는 기능 추가
> ✨ 로그인 / 로그아웃 전환

- dv/lib/menu/menu.dart
> ⚡️ 로그인/아웃 변수설정 및 로그아웃 메시지 추가

- dv/lib/mypage/my_page_screen.dart
- dv/lib/tabbar/tab_bar_screen.dart
> ✨ Mypage 생성

- dv/lib/login/login_page.dart
- dv/lib/main.dart
- dv/lib/menu/menu.dart
- dv/lib/menu/menu_provider.dart
- dv/lib/mypage/my_page_screen.dart
- dv/lib/settings/setting_screen.dart
> ✨ 메뉴에서 현재 위치하고 있는 선택지 삭제

- dv/lib/gallery/photo.dart
- dv/lib/login/login_required_page.dart
> ⚡️ 로그인x 시 보관함 페이지 변경

- dv/lib/login/login_provider.dart
- dv/lib/login/login_success_page.dart
- dv/lib/title/title_screen.dart
앱을 재시작했을 때 로그인 상태를 반영하여 로그인 상태이면 홈 화면, 로그아웃 상태이면 로그인 화면으로 이동
> 🎨 로그인 상태 반영

- dv/lib/gallery/showroom.dart
- dv/lib/login/login_required_page.dart
> 🎨 로그인이 필요합니다 창 언어/색상 반영

- dv/lib/login/login_page.dart
- dv/lib/menu/menu.dart
- dv/lib/mypage/my_page_screen.dart
- dv/lib/settings/language/language_provider.dart
- dv/lib/settings/setting_screen.dart
- dv/lib/settings/theme/color_palette.dart
- dv/lib/settings/theme/theme_provider.dart
마이 페이지 안으로 설정 버튼 이동. 설정 창 내에서 변경된 사항 마이 페이지에서 반영 뒤 페이지 빌드.
> ✨ 마이 페이지 안으로 설정 버튼 이동

- dv/lib/menu/menu.dart
- dv/lib/mypage/my_page_logout_screen.dart
- dv/lib/shop/shop_screen.dart
마이 페이지에서 프로필 편집 기능 제한. 포인트 상점 구매 기능 제한
> ✨ 로그아웃 시 마이페이지 / 포인트 상점 기능 제한

- dv/lib/shop/shop_item_provider.dart
- dv/lib/shop/shop_items.dart
- dv/lib/shop/shop_screen.dart
> 💡 Shop 폴더 내 파일 주석

- dv/lib/sign_up/sign_up_screen.dart
> ✨ 회원가입 창 생성

- dv/lib/sign_up/account_list.dart
> ✨ 사용자 계정 정보

- dv/lib/login/login_page.dart
- dv/lib/sign_up/account_list.dart
- dv/lib/sign_up/sign_up_rules.dart
- dv/lib/sign_up/sign_up_screen.dart
- dv/lib/sign_up/sign_up_success_screen.dart
이메일 비밀번호 조건 충족 시 회원가입 성공하도록 기능 도입. 회원가입 성공 시 환영 페이지 뜨도록.
> ✨ 회원가입 화면 및 기능 완성

- dv/lib/main.dart
- dv/lib/mypage/my_page_screen.dart
- dv/lib/nickname/nickname_provider.dart
> ✨ 마이 페이지의 닉네임 란에 닉네임 반영

- dv/lib/main.dart
- dv/lib/mypage/my_page_screen.dart
- dv/lib/shop/shop_provider.dart
- dv/lib/shop/shop_screen.dart
- dv/lib/sign_up/account_list.dart
> ✨ 마이 페이지에 포인트 내용 연동

- dv/lib/gallery/image_provider.dart
- dv/lib/gallery/photo.dart
- dv/lib/gallery/photo_features/design_/title_flag.dart
- dv/lib/gallery/photo_features/design_/title_flag_painter.dart
- dv/lib/gallery/photo_features/edit_image_dialog.dart
- dv/lib/gallery/photo_features/gallery_check_overlay.dart
- dv/lib/gallery/photo_features/photo_display.dart
- dv/lib/gallery/photo_features/photo_picker.dart
- dv/lib/gallery/photo_features/photo_utils.dart
- dv/lib/gallery/showroom.dart
1. photo_features와 design_(디자인관련파일) 폴더로 구분해서 각각 세분화 파일을 만듦
2. 수정버튼 수정 완료^^(처음 업로드시랑 창 같은 디자인으로 변경)
3. 기타 기능 복원 및 수정 
#103
> ⚡️ 갤러리(photo)파일 쪼개서 세분화 및 디자인, 버그 수정

- dv/lib/gallery/showroom.dart
- dv/lib/gallery/showroom_features/show_image_dialog.dart
- dv/lib/gallery/showroom_features/showroom_body.dart
- dv/lib/gallery/showroom_features/showroom_grid_item.dart
- dv/lib/gallery/showroom_features/showroom_header.dart
gallery 폴더에 showroom_features 폴더를 만들고 안에 showroom 파일 쪼갠 것들 넣어놨습니다(차후 수정을 용이하게 하기 위함)
> 🌱 Showroom.dart 파일 세분화

- dv/lib/follow_up/pages/follow_list_page.dart
- dv/lib/follow_up/providers/follow_provider.dart
- dv/lib/follow_up/widgets/follow_list_item.dart
- dv/lib/gallery/showroom.dart
- dv/lib/gallery/showroom_features/show_image_dialog.dart
- dv/lib/gallery/showroom_features/showroom_body.dart
- dv/lib/gallery/showroom_features/showroom_grid_item.dart
- dv/lib/gallery/showroom_features/showroom_header.dart
- dv/lib/main.dart
이아래 내용들 눌러보심 될듯 각각 
1. showroom 파일 세분화
2. 팔로잉 목록 페이지
입니다
> 이거 왜 따로따로 풀리퀘스트가안됨? 일단해볼테니 확인해주십시오 

- dv/lib/firebase_login/get_user_data.dart
- dv/lib/main.dart
- dv/lib/menu/menu.dart
- dv/lib/mypage/my_page_screen.dart
- dv/lib/sign_up/sign_up_success_screen.dart
> ✨ 마이페이지에 db내용 연동

- dv/lib/firebase_login/get_user_data.dart
- dv/lib/firebase_login/signup_login.dart
- dv/lib/mypage/my_page_edit.dart
- dv/lib/mypage/my_page_screen.dart
마이페이지 창에서 닉네임 편집할 수 있도록 기능 추가.
> ✨ 마이페이지에서 닉네임 편집

- dv/lib/shop/shop_provider.dart
- dv/lib/shop/shop_screen.dart
상점 이용 중 구매 아이템의 가격보다 보유 포인트가 적은 경우 경고창이 뜨도록 기능 추가
> ✨ 포인트 부족 경고창 생성

- dv/.firebaserc
- dv/cors.json
- dv/firebase.json
- dv/firestore.indexes.json
- dv/firestore.rules
- dv/lib/firebase_upload/post_service.dart
- dv/lib/gallery/image_provider.dart
- dv/lib/gallery/photo.dart
- dv/storage.rules
> ✨ 게시글 db에서 불러오기

- dv/lib/gallery/image_provider.dart
- dv/lib/gallery/photo.dart
- dv/pubspec.lock
게시글 업로드 이후 화면 업데이트 시점이 서버에서 게시글을 불러오는 시점보다 빨라서 null이 뜨는 오류 발생. 사이에 로딩 을 넣어서 문제 해결.
> 🐛 게시글 업로드 시 null 뜨는 오류 해결

- dv/lib/firebase_login/signup_login_screen.dart
- dv/lib/settings/theme/theme_images.dart
> 🎨 로그인 화면 테마 적용

- dv/lib/category/category_screen.dart
- dv/lib/firebase_upload/post_service.dart
카테고리 별로 검색창에 게시글 최신순으로 나열
검색 기능 작동하는 것 확인 완료.
> ✨ 카테고리 검색창에 게시글 표시, 검색 기능 작동 확인

- dv/lib/category/category_post_screen.dart
- dv/lib/category/category_screen.dart
- dv/lib/firebase_upload/post_service.dart
- dv/pubspec.lock
- dv/pubspec.yaml
검색 결과에 나오는 게시글 눌렀을 때
- 작성자 프로필 사진, 닉네임
- 작성 연월일시분
- 제목
- 사진
- 글 내용
하단에 하트 누르는 기능 추가
- 이미 누른 하트 취소 불가
- 옆에 카운트 표시
- 눌렀을 경우 작성자에게 50pt 지급
> ✨ 게시글 눌렀을 때 해당 게시글 불러오기 및 다른 사람 게시물에 반응 추가

- dv/lib/category/category_post_screen.dart
자신이 하트를 누른 게시글의 하트는 항상 빨간색이도록 수정.
> 💄 하트 누른 게시글에는 하트가 항상 빨간색이도록 수정

- dv/lib/firebase_login/get_user_data.dart
- dv/lib/gallery/photo_features/edit_image_dialog.dart
- dv/lib/main.dart
- dv/lib/settings/theme/theme_images.dart
- dv/lib/shop/shop_provider.dart
- dv/lib/shop/shop_screen.dart
- dv/lib/shop/user_points_provider.dart
> ⚡️ 포인트샵 포인트 계정별 연동

- dv/lib/category/category_post_screen.dart
- dv/lib/gallery/photo.dart
- dv/lib/gallery/photo_features/photo_display.dart
- dv/lib/others_gallery/others_gallery_screen.dart
나의 보관함 화면에서 이미지 삭제 시 바로 반영 안되는 문제 해결.
카테고리 - 게시글에서 프로필 눌렀을 때 바로 이동 안하고 Null 화면 떴다가 이동하는 문제 해결.
- 로딩 화면 삽입
> 🐛 이미지 삭제 시 화면 업데이트 안되는 문제 수정.  게시글에서 프로필 눌러서 사용자로 넘어갈 때 Null 화면 뜨는 문제 수정.

- dv/lib/settings/setting_screen.dart
- dv/lib/settings/update_password/update_password.dart
설정에 비밀번호 변경 기능 추가
- 새로운 비밀번호 입력란과 확인란을 만들어 두 곳에 입력한 비밀번호가 일치해야 변경.
> ✨ 설정에 비밀번호 변경 기능 추가

- dv/lib/menu/menu.dart
- dv/lib/shop/shop_screen.dart
> ✨ 포인트샵 로그아웃 상태 반영

- dv/lib/firebase_login/signup_login.dart
- dv/lib/shop/shop_provider.dart
- dv/lib/shop/shop_screen.dart
- dv/lib/shop/user_points_provider.dart
> ⚡️ 포인트상점에서 구매내역 저장되게 수정

- dv/lib/mypage/choose_profile.dart
- dv/lib/mypage/my_page_edit.dart
> ⚡️ 프로필사진 포인트샵과 연동완료

- dv/lib/gallery/photo_features/photo_display.dart
- dv/lib/shop/shop_screen.dart
> 🐛 포인트샵 로그아웃-로그인해도 구매내역 유지되게 수정

- dv/lib/firebase_upload/post_service.dart
- dv/lib/gallery/photo_features/photo_display.dart
- dv/lib/gallery/showroom.dart
> ✨ 갤러리 추가버튼 복구 완료

- dv/lib/gallery/recommendation_page.dart
- dv/lib/gallery/swipe_page_view.dart
> ✨ 추천페이지 개설 및 스와이프 이동

- dv/lib/mypage/collection/collection_screen.dart
> ⚡️ 수집목록 사이즈 및 오류 수정

- dv/lib/gallery/photo_features/photo_display.dart
> ⚡️ Photo_display 디자인 수정

- dv/lib/firebase_login/signup_login_screen.dart
- dv/lib/login/login_page.dart
- dv/lib/main.dart
- dv/lib/sign_up/sign_up_screen.dart
회원가입 페이지 정보 입력 시 라벨, border 사라지는 것 수정
> 💄 회원가입 페이지 form 디자인 오류 수정

- dv/lib/gallery/photo_features/photo_display.dart
- dv/lib/gallery/photo_features/photo_picker.dart
- dv/lib/sign_up/sign_up_screen.dart
배경색,텍스트박스 테두리 색, 글자 색, 버튼색  테마 적용
> 🎨 보관함 사진 추가 및 사진 자세히 보기 창 컬러 테마 적용
